# Generated by Django 4.2.2 on 2023-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
